CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TABLE "Authors" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "BirthDate" timestamp with time zone,
    "IsDeleted" boolean NOT NULL,
    "CreatedDate" timestamp with time zone NOT NULL,
    "UpdatedDate" timestamp with time zone,
    CONSTRAINT "PK_Authors" PRIMARY KEY ("Id")
);

CREATE TABLE "Categories" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "ParentCategoryId" integer,
    "IsDeleted" boolean NOT NULL,
    "CreatedDate" timestamp with time zone NOT NULL,
    "UpdatedDate" timestamp with time zone,
    CONSTRAINT "PK_Categories" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Categories_Categories_ParentCategoryId" FOREIGN KEY ("ParentCategoryId") REFERENCES "Categories" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "Customers" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "Email" text NOT NULL,
    "Phone" text NOT NULL,
    "IsDeleted" boolean NOT NULL,
    "CreatedDate" timestamp with time zone NOT NULL,
    "UpdatedDate" timestamp with time zone,
    CONSTRAINT "PK_Customers" PRIMARY KEY ("Id")
);

CREATE TABLE "Personnel" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "Email" text NOT NULL,
    "Role" text NOT NULL,
    "IsDeleted" boolean NOT NULL,
    "CreatedDate" timestamp with time zone NOT NULL,
    "UpdatedDate" timestamp with time zone,
    CONSTRAINT "PK_Personnel" PRIMARY KEY ("Id")
);

CREATE TABLE "Books" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Title" text NOT NULL,
    "ISBN" text NOT NULL,
    "AuthorId" integer NOT NULL,
    "CategoryId" integer NOT NULL,
    "PublisherName" text NOT NULL,
    "PageCount" integer NOT NULL,
    "IsDeleted" boolean NOT NULL,
    "CreatedDate" timestamp with time zone NOT NULL,
    "UpdatedDate" timestamp with time zone,
    CONSTRAINT "PK_Books" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Books_Authors_AuthorId" FOREIGN KEY ("AuthorId") REFERENCES "Authors" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Books_Categories_CategoryId" FOREIGN KEY ("CategoryId") REFERENCES "Categories" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Loans" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "CustomerId" integer NOT NULL,
    "PersonnelId" integer NOT NULL,
    "LoanDate" timestamp with time zone NOT NULL,
    "ReturnDate" timestamp with time zone,
    "IsReturned" boolean NOT NULL,
    "IsDeleted" boolean NOT NULL,
    "CreatedDate" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Loans" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Loans_Customers_CustomerId" FOREIGN KEY ("CustomerId") REFERENCES "Customers" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Loans_Personnel_PersonnelId" FOREIGN KEY ("PersonnelId") REFERENCES "Personnel" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Stocks" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "BookId" integer NOT NULL,
    "Quantity" integer NOT NULL,
    "LastUpdated" timestamp with time zone NOT NULL,
    "IsDeleted" boolean NOT NULL,
    CONSTRAINT "PK_Stocks" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Stocks_Books_BookId" FOREIGN KEY ("BookId") REFERENCES "Books" ("Id") ON DELETE CASCADE
);

CREATE TABLE "LoanDetails" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "LoanId" integer NOT NULL,
    "BookId" integer NOT NULL,
    "ReturnDate" timestamp with time zone NOT NULL,
    "IsLost" boolean NOT NULL,
    "IsDeleted" boolean NOT NULL,
    CONSTRAINT "PK_LoanDetails" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_LoanDetails_Books_BookId" FOREIGN KEY ("BookId") REFERENCES "Books" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_LoanDetails_Loans_LoanId" FOREIGN KEY ("LoanId") REFERENCES "Loans" ("Id") ON DELETE CASCADE
);

CREATE TABLE "StockLogs" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "StockId" integer NOT NULL,
    "PersonnelId" integer NOT NULL,
    "Action" text NOT NULL,
    "ChangeAmount" integer NOT NULL,
    "Date" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_StockLogs" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_StockLogs_Personnel_PersonnelId" FOREIGN KEY ("PersonnelId") REFERENCES "Personnel" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_StockLogs_Stocks_StockId" FOREIGN KEY ("StockId") REFERENCES "Stocks" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_Books_AuthorId" ON "Books" ("AuthorId");

CREATE INDEX "IX_Books_CategoryId" ON "Books" ("CategoryId");

CREATE INDEX "IX_Categories_ParentCategoryId" ON "Categories" ("ParentCategoryId");

CREATE INDEX "IX_LoanDetails_BookId" ON "LoanDetails" ("BookId");

CREATE INDEX "IX_LoanDetails_LoanId" ON "LoanDetails" ("LoanId");

CREATE INDEX "IX_Loans_CustomerId" ON "Loans" ("CustomerId");

CREATE INDEX "IX_Loans_PersonnelId" ON "Loans" ("PersonnelId");

CREATE INDEX "IX_StockLogs_PersonnelId" ON "StockLogs" ("PersonnelId");

CREATE INDEX "IX_StockLogs_StockId" ON "StockLogs" ("StockId");

CREATE UNIQUE INDEX "IX_Stocks_BookId" ON "Stocks" ("BookId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250318154216_InitialCreate', '9.0.3');

COMMIT;

